server: 
  port: 8082

spring:
  applocation: 
    name: xiuyuCloud
 
eureka: 
  instance:
    instance-id: xiuyuCloud-8082
    prefer-ip-address: true  #设置访问路径可以显示 IP 地址
  client: 
    register-with-eureka: true #false表示不向注册中心注册自己。
    fetch-registry: true       #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka-10010.com:10012/eureka/,http://eureka-10011.com:10011/eureka/,http://eureka-10010.com:10010/eureka/